version: '3'  

services:  
  front-poke: 
    container_name: front-poke-app
    build: ./frontend-pokemon-app
    ports:
      - 3000:3000
    depends_on:
      - back-poke
    networks:
      - poke  

  back-poke:
    container_name: back-poke-app
    build: ./backend-pokemon-app
    ports:
      - 8000:8000
    networks:
      - poke    

networks:
  poke:
    driver: bridge